version: "3.8"

services:
  comfyui:
    build: .
    # Expose all NVIDIA GPUs to this service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      # Ensure the container has full GPU visibility
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # (Optional) extra ComfyUI CLI args
      - CLI_ARGS=--listen 0.0.0.0 --port 8188
    volumes:
      # Persist your models, workflows, and custom nodes
      - sdmodels:/root/ComfyUI/models
      - comfy_data:/root/ComfyUI/data
    ports:
      - "8188:8188"
volumes:
  sdmodels:
  comfy_data:
